NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2023"
ACCOUNTS=[
"GAFS2ZAEEEQIRXYP75FQIAHDYVE3NCNIZB4ACIMYY3JB4RAS2QYTCE2J",
"GAJHI6COUP6GH7HE3PMPHWZC4IX33Y6H4KJ6R25ZVP6LCPSTNAILAOWT",
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Great Hub"
ORG_URL="https://www.not-a-link.com"
ORG_LOGO="https://www.not-a-link.com/awesomelogo.png"
ORG_PHYSICAL_ADDRESS="74 Aluu road Rumuekini Rivers State Nigeria"
ORG_OFFICIAL_EMAIL="adamsgreat01@gmail.com"
ORG_SUPPORT_EMAIL="kingifean@gmail.com"

[[PRINCIPALS]]
name="Great Ifeanyichukwu Adams"
email="kingifean@gmail.com"
keybase="greatAdams01"
twitter="greatAdams01"
github="greatAdams01"

# asset with meta info
[[CURRENCIES]]
code="GA"
issuer="GAFS2ZAEEEQIRXYP75FQIAHDYVE3NCNIZB4ACIMYY3JB4RAS2QYTCE2J"
display_decimals=2
name="GreatAdams01"
desc="This is a test for GreatAdams01 tokens"
conditions="There will only ever be 10,000 GA tokens in existence. We will distribute the revenue share annually on Jan. 15th"
image="https://not-a-valid-link/png/2292360-200.png"
fixed_number=10000
